name: Scorecards supply-chain security
on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
jobs:
  analyze:
    permissions:
      security-events: write
      actions: read
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run OpenSSF Scorecard
        uses: ossf/scorecard-action@v2.5.1
